version: "3.8"

services:
  node1:
    build:
      context: ./node1
      dockerfile: Dockerfile
    container_name: node1
    ports:
      - "2281:22"

  node2:
    build:
      context: ./node2
      dockerfile: Dockerfile
    container_name: node2
    ports:
      - "2282:22"